config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "link_entries#index"

  resources :link_entries, path: '/', only: [:new, :create, :destroy]

  get "/:short_id", to: "link_entries#perform_redirect", as: :link_entry_redirect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link_entry.rb
class LinkEntry < ApplicationRecord
  before_create :set_short_id

  validates :external_url, presence: true

  def self.get_external_url(short_id)
    Rails.cache.fetch("short_id/#{short_id}") do
      self.find_by!(short_id: short_id).external_url
    end
  end
  
private
  def set_short_id
    self.short_id = Digest::SHA1.hexdigest(SecureRandom.uuid)[...10]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/link_entries_controller.rb
class LinkEntriesController < ApplicationController
  def index
    @link_entries = LinkEntry.all
  end

  def new
    @link_entry = LinkEntry.new
  end

  def create
    @link_entry = LinkEntry.new(link_entry_params)

    if @link_entry.save
      redirect_to :link_entries
    else
      render :new, status: :unprocessable_entity
    end
  end

  def perform_redirect
    external_url = LinkEntry.get_external_url(params[:short_id])

    redirect_to external_url, allow_other_host: true
  end

  def destroy
    e = LinkEntry.find(params[:id])
    e.destroy
    redirect_to :link_entries
  end

private
  def link_entry_params
    params.require(:link_entry).permit(:external_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_entries_helper.rb
module LinkEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YausWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to_unless_current "Home", root_path %>
      <%= link_to_unless_current "Create new", new_link_entry_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/link_entries/index.html.erb
<h1> All Link Entries </h1>

<table>
    <thead>
        <th>Short URL</th>
        <th>External URL</th>
        <th></th>
    </thead>
    <tbody>
        <% @link_entries.each do |e| %>
            <tr>
                <td><%= link_to link_entry_redirect_url(short_id: e.short_id), link_entry_redirect_url(short_id: e.short_id) %></td>
                <td><%= link_to e.external_url, e.external_url %></td>
                <td><%= button_to "delete", e, :method => :delete %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/link_entries/new.html.erb
<% if @link_entry.errors.any? %>
    <% @link_entry.errors.full_messages.each do |message|%>
        <h3><%= message %></h3>
    <%end%>
<%end%>

</br>

<%= form_with model: @link_entry do |form| %>
    <%= form.text_field :external_url %>
    <%= form.submit %>
<% end %>